apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-app
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: apps
    repoURL: 'git@github.com:steve-dean-mercer/devops.git'
    targetRevision: HEAD
  project: default
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
