apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: devops
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/steve-dean-mercer/devops.git
  ref:
    branch: master
