kind: Service
apiVersion: v1
metadata:
  name: argocd-svc
  namespace: argocd
  annotations:
    metallb.universe.tf/allow-shared-ip: argocdserver 
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  ports:                      
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.0.52