apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-subdir-external-provisioner
    app.kubernetes.io/instance: nfs-subdir-external-provisioner
    chart: nfs-subdir-external-provisioner-4.0.18
    heritage: Helm
    release: nfs-subdir-external-provisioner
  name: nfs-subdir-external-provisioner
  namespace: nfs-subdir-external-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-subdir-external-provisioner
      release: nfs-subdir-external-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: null
      labels:
        app: nfs-subdir-external-provisioner
        release: nfs-subdir-external-provisioner
    spec:
      containers:
        - env:
            - name: PROVISIONER_NAME
              value: cluster.local/nfs-subdir-external-provisioner
            - name: NFS_SERVER
              value: null
            - name: NFS_PATH
              value: /nfs-storage
          image: 'registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2'
          imagePullPolicy: IfNotPresent
          name: nfs-subdir-external-provisioner
          securityContext: {}
          volumeMounts:
            - mountPath: /persistentvolumes
              name: nfs-subdir-external-provisioner-root
      securityContext: {}
      serviceAccountName: nfs-subdir-external-provisioner
      volumes:
        - name: nfs-subdir-external-provisioner-root
          nfs:
            path: /nfs-storage
            server: '192.168.0.110'