apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 'v0.14.5'
    helm:
      valuesObject:
        configInline:
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            - 192.168.0.50-192.168.0.70
  destination:
    namespace: metallb-system
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
