# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: nfs-subdir-external-provisioner-2
#   namespace: argocd
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
#     chart: nfs-subdir-external-provisioner
#     targetRevision: 'v4.0.18'
#     helm:
#       parameters:
#         - name: nfs.server
#           value: '192.168.0.110'
#         - name: nfs.path
#           value: '/mnt/my_external_2'
#         - name: storageClass.name
#           value: 'nfs-client-2'
#         - name: storageClass.name
#           value: 'second-nfs-subdir-external-provisioner'
#   destination:
#     namespace: nfs-subdir-external-provisioner
#     name: in-cluster
#   syncPolicy:
#     automated: {}
#     syncOptions:
#       - CreateNamespace=true
#       - ServerSideApply=true
