apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    chart: plex-media-server
    targetRevision: 'v0.3.0'
    helm:
      valuesObject:
        pms:
          storageClassName: "longhorn"
          configStorage: "5Gi"
        extraVolumeMounts:
          - name: plex-storage
            mountPath: /data/plex
        extraVolumes:
          - name: plex-storage
            persistentVolumeClaim:
              claimName: plex-pvc
  destination:
    namespace: plex
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
