apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    chart: plex-media-server
    targetRevision: 'v0.2.0'
    helm:
      parameters:
        - name: pms.storageClassName
          value: "longhorn"
        - name: pms.configStorage
          value: "2Gi"
  destination:
    namespace: plex
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
