# pod-with-pvc.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc
spec:
  storageClassName: second-nfs-subdir-external-provisioner
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 2Ti } }
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx
# spec:
#   volumes:
#     - name: pvc
#       persistentVolumeClaim:
#         claimName: nginx-pvc
#   containers:
#     - name: nginx
#       image: nginx:latest
#       ports:
#         - containerPort: 80
#       volumeMounts:
#         - name: pvc
#           mountPath: /usr/share/nginx/html