apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbitorrent
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.gabe565.com/
    chart: qbittorrent
    targetRevision: 'v0.3.4'
    helm:
      valuesObject:
       persistence:
        config:
          enabled: true
          retain: true
          storageClass: "longhorn"
          accessMode: ReadWriteOnce
          size: 1Gi
        downloads:
          enabled: true
          mountPath: /downloads
          storageClass: "nfs-client"
          accessMode: ReadWriteMany
          size: 100Gi
  destination:
    namespace: plex
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
