kind: Service
apiVersion: v1
metadata:
  name: vault-svc
  namespace: vault
  annotations:
    metallb.universe.tf/allow-shared-ip: vault
spec:
  selector:
    app.kubernetes.io/name: vault
  ports:                      
  - port: 8200
    targetPort: 8200
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.0.54
