---
- name: Install k8s
  hosts: all
  become: yes
  tasks:
    - name: Check if kubeadm is installed
      command: which kubeadm
      register: kubeadm_check
      ignore_errors: true
      changed_when: false

    - block:
        - name: Update and Upgrade Packages
          apt:
            update_cache: yes
            upgrade: dist

        - name: Disable Swap
          command: swapoff -a
          ignore_errors: true

        - name: Comment Swap in fstab
          lineinfile:
            path: /etc/fstab
            regexp: '^\s*[^#].*swap\s'
            line: '#\0'

        - name: Add Kernel Modules
          copy:
            dest: /etc/modules-load.d/containerd.conf
            content: |
              overlay
              br_netfilter

        - name: Load Kernel Modules
          modprobe:
            name: "{{ item }}"
            state: present
          loop:
            - overlay
            - br_netfilter

        - name: Add sysctl settings
          copy:
            dest: /etc/sysctl.d/kubernetes.conf
            content: |
              net.bridge.bridge-nf-call-ip6tables = 1
              net.bridge.bridge-nf-call-iptables = 1
              net.ipv4.ip_forward = 1
          notify:
            - reload sysctl

        - name: Install Containerd Dependencies
          apt:
            name:
              - curl
              - gnupg2
              - software-properties-common
              - apt-transport-https
              - ca-certificates
            state: present

        - name: Add Docker GPG key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add Docker Repository
          apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
            state: present

        - name: Install Containerd
          apt:
            name: containerd.io
            state: present
          notify:
            - restart containerd

        - name: Configure Containerd
          blockinfile:
            path: /etc/containerd/config.toml
            block: |
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
              SystemdCgroup = true

        - name: Import Kubernetes GPG key
          apt_key:
            url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
            state: present

        - name: Add Kubernetes Repo
          apt_repository:
            repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
            state: present

        - name: Install Kubernetes Components
          apt:
            name:
              - kubelet
              - kubeadm
              - kubectl
            state: present
            update_cache: yes

        - name: Hold Kubernetes Packages
          dpkg_selections:
            name: "{{ item }}"
            selection: hold
          loop:
            - kubelet
            - kubeadm
            - kubectl
      when: kubeadm_check.rc != 0

  handlers:
    - name: reload sysctl
      command: sysctl --system

    - name: restart containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes
