---
- name: Install k8s
  hosts: control_plane
  become: yes
  vars:
    kubernetes_version: "1.28.2-00"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Disable swap
      command: swapoff -a
      ignore_errors: true

    - name: Remove swap from /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^(\s*[^#\s]+\s+swap\s+\S+\s+\S+\s*)$'
        line: '#\1'
        backrefs: yes

    - name: Install container runtime (containerd)
      block:
        - name: Install containerd
          apt:
            name: containerd
            state: present
            update_cache: yes

        - name: Create containerd configuration file
          command: containerd config default | tee /etc/containerd/config.toml
          args:
            creates: /etc/containerd/config.toml

        - name: Restart and enable containerd
          systemd:
            name: containerd
            state: restarted
            enabled: yes

    - name: Set sysctl parameters for Kubernetes networking
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      loop:
        - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
        - { name: 'net.ipv4.ip_forward', value: '1' }
      when: ansible_os_family == "Debian"

    - name: Check current kubeadm version
      command: kubeadm version -o short
      register: current_kubeadm_version
      changed_when: false
      ignore_errors: true

    - name: Install kubeadm 
      block:
        - name: Update all packages
          apt:
            update_cache: yes

        - name: Install transport-https and software-properties-common
          apt:
            name:
              - apt-transport-https
              - software-properties-common
            state: present

        - name: Add Kubernetes signing key
          ansible.builtin.apt_key:
            url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
            state: present

        - name: Add Kubernetes repository
          ansible.builtin.apt_repository:
            repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
            state: present
            filename: kubernetes

        - name: Install kubeadm
          apt:
            name: "kubeadm={{ kubernetes_version }}"
            state: present
            update_cache: yes

        - name: Hold kubeadm at the specified version
          ansible.builtin.dpkg_selections:
            name: kubeadm
            selection: hold
      when: current_kubeadm_version.stdout is not search(kubernetes_version)

    - name: Verify kubeadm installation
      command: kubeadm version -o short
      register: kubeadm_version
      changed_when: false

    - name: Show kubeadm version
      debug:
        var: kubeadm_version.stdout_lines
