---
- name: Ensure Python is installed
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Check if Python is installed
      raw: python --version || python3 --version
      register: python_installed
      ignore_errors: yes

    - name: Install Python 3
      raw: sudo apt-get update && sudo apt-get install -y python3
      when: python_installed is failed
