name: Run Ansible Playbook

on:
  push:
    branches:
      - main
      - actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: playbook.yaml
        directory: ./ansible
        configuration: |
          [defaults]
          callbacks_enabled = ansible.posix.profile_tasks, ansible.posix.timer
          stdout_callback = yaml
          nocows = false
        inventory: |
          [all]
          ${{ secrets.CONTROL_PLANE_HOST }}
        vault_password: ${{ secrets.VAULT_PASSWORD }}
